# Generated by Django 5.2.4 on 2026-05-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='Qurilma ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Sensor nomi')),
                ('sensor_type', models.CharField(choices=[('soil_moisture', 'Tuproq namligi'), ('soil_temp', 'Tuproq harorati'), ('air_temp', 'Havo harorati'), ('air_humidity', 'Havo namligi'), ('rainfall', "Yog'ingarchilik"), ('flow_meter', 'Suv sarfi'), ('solar_rad', 'Quyosh radiatsiyasi')], max_length=50, verbose_name='Sensor turi')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('status', models.CharField(choices=[('online', 'Onlayn'), ('offline', 'Oflayn'), ('error', 'Xato')], default='offline', max_length=20, verbose_name='Holat')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('firmware_ver', models.CharField(blank=True, max_length=20, verbose_name='Firmware versiyasi')),
                ('secret_key', models.CharField(blank=True, max_length=64, verbose_name='Maxfiy kalit')),
                ('low_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pastki chegara')),
                ('high_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Yuqori chegara')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name="O'lchov birligi")),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farms.field', verbose_name='Dala')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensorlar',
                'ordering': ['field', 'sensor_type'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Qiymat')),
                ('unit', models.CharField(max_length=20, verbose_name='Birlik')),
                ('quality', models.SmallIntegerField(default=100, verbose_name='Sifat (%)')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': "Sensor o'lchovi",
                'verbose_name_plural': "Sensor o'lchovlari",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', 'timestamp'], name='sensors_sen_sensor__6ce6a7_idx')],
            },
        ),
    ]
