# Generated by Django 5.2.4 on 2026-05-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_moisture', 'Tuproq namligi past'), ('high_moisture', 'Tuproq namligi yuqori'), ('device_offline', 'Qurilma offline'), ('irrigation_failed', "Sug'orish xatosi"), ('rain_detected', "Yomg'ir aniqlandi"), ('low_battery', 'Batareya past')], max_length=50, verbose_name='Ogohlantirish turi')),
                ('severity', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('critical', 'Muhim')], max_length=20, verbose_name='Jiddiylik darajasi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Qiymat')),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Chegara')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal qilindi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
            ],
            options={
                'verbose_name': 'Ogohlantirish',
                'verbose_name_plural': 'Ogohlantirishlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
