# Generated by Django 5.2.4 on 2026-05-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jadval nomi')),
                ('trigger_type', models.CharField(choices=[('time', "Vaqt bo'yicha"), ('sensor', "Sensor bo'yicha"), ('weather', "Ob-havo bo'yicha")], default='time', max_length=20, verbose_name='Ishga tushirish turi')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('days_of_week', models.JSONField(default=list, help_text='[1,2,3,4,5] - Dushanba-Juma', verbose_name='Hafta kunlari')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (daqiqa)')),
                ('soil_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Sensor trigger uchun', max_digits=5, null=True, verbose_name='Tuproq namligi chegarasi (%)')),
                ('target_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maqsadli namlik (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('pause_on_rain', models.BooleanField(default=True, verbose_name="Yomg'irda to'xtatish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': "Sug'orish jadvali",
                'verbose_name_plural': "Sug'orish jadvallari",
                'ordering': ['field', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', "Qo'lda"), ('schedule', "Jadval bo'yicha"), ('sensor', "Sensor bo'yicha"), ('weather', "Ob-havo bo'yicha")], max_length=20, verbose_name='Ishga tushirish turi')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('duration_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('water_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sarflangan suv (litr)')),
                ('status', models.CharField(choices=[('running', 'Davom etmoqda'), ('completed', 'Yakunlandi'), ('stopped', "To'xtatildi"), ('failed', 'Xato')], default='running', max_length=20, verbose_name='Holat')),
                ('stop_reason', models.CharField(blank=True, max_length=100, verbose_name="To'xtatish sababi")),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='farms.field', verbose_name='Dala')),
            ],
            options={
                'verbose_name': "Sug'orish hodisasi",
                'verbose_name_plural': "Sug'orish hodisalari",
                'ordering': ['-started_at'],
            },
        ),
    ]
