# Generated by Django 5.2.4 on 2026-05-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ferma nomi')),
                ('region', models.CharField(choices=[('tashkent', 'Toshkent'), ('tashkent_region', 'Toshkent viloyati'), ('andijan', 'Andijon'), ('bukhara', 'Buxoro'), ('fergana', "Farg'ona"), ('jizzakh', 'Jizzax'), ('kashkadarya', 'Qashqadaryo'), ('khorezm', 'Xorazm'), ('namangan', 'Namangan'), ('navoi', 'Navoiy'), ('samarkand', 'Samarqand'), ('sirdarya', 'Sirdaryo'), ('surkhandarya', 'Surxondaryo'), ('karakalpakstan', "Qoraqalpog'iston")], max_length=50, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kenglik (latitude)')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Uzunlik (longitude)')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy maydon (gektar)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Ferma',
                'verbose_name_plural': 'Fermalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dala nomi')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maydon (gektar)')),
                ('crop_type', models.CharField(choices=[('cotton', 'Paxta'), ('wheat', "Bug'doy"), ('vegetable', 'Sabzavot'), ('fruit', 'Meva'), ('rice', 'Sholi'), ('other', 'Boshqa')], max_length=50, verbose_name='Ekin turi')),
                ('irr_method', models.CharField(choices=[('drip', "Tomchilatib sug'orish"), ('sprinkler', "Yomg'irlatib sug'orish"), ('surface', "Sirt sug'orish"), ('subsurface', "Yer osti sug'orish")], max_length=50, verbose_name="Sug'orish usuli")),
                ('soil_type', models.CharField(blank=True, choices=[('loam', 'Loy tuproq'), ('clay', "Loy tuproq (og'ir)"), ('sandy', 'Qumli tuproq'), ('saline', "Sho'r tuproq"), ('silty', 'Loyqa tuproq')], max_length=50, verbose_name='Tuproq turi')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='Ekish sanasi')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name="Hosilni yig'ish sanasi")),
                ('polygon_json', models.JSONField(blank=True, null=True, verbose_name='Dala chegaralari (GeoJSON)')),
                ('kc_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Ekin koeffitsienti (Kc)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Dala',
                'verbose_name_plural': 'Dalalar',
                'ordering': ['farm', 'name'],
            },
        ),
    ]
